import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import Header from "./components/layouts/Header";
import { ThemeProvider } from "next-themes";
import ThemeSwitcher from "./components/layouts/ThemeSwitcher";
import { ToastContainer } from "./components/ui/toast";
import "./globals.css";

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
  weight: ["600"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${comfortaa.variable} antialiased font-sans min-h-screen`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <main className="pt-20 flex flex-col items-center justify-center min-h-screen">
            {children}
          </main>
          <ToastContainer />
        </ThemeProvider>
      </body>
    </html>
  );
}
